image: node:10-alpine

before_script:
  - apk add --no-cache lftp

pages:
  script:
    - npm install
    - ./node_modules/.bin/gatsby build --prefix-paths
    - cd public
    - lftp -e "mirror -R ./; bye" -u hmsa,${FTP_PASSWORD} appstore.asynchrony.com
  only:
    - master
  tags:
    - docker
